### ISSUE TITLE
hello from a fellow data engineer

### ISSUE THREAD

**Issue by jonathandbyrd** [mdrakiburrahman/rakirahman.me#12]
Hi Raki (As-salaamu alaykum)

i have been reading some of your blog posts with amazement. You have incredible graphics but also have some great stuff on Azure + Databricks. If you have any time, i'd love to ask you an architecture design question that I am struggling with, one of your posts i think answers it for me, but wanted to run it by you.

Thank you,
Jonathan

**Comment by mdrakiburrahman** [comment]
Hi @jonathandbyrd, 

Walaikum Salam. Thanks for the kind words!

Sure, go for it - I'll keep my eye out for notifications here. I will share try my best to help.

**Comment by jonathandbyrd** [comment]
i should probably do this in markdown but i think i can explain it

we want to implement a databricks (DB) solution where, we have small json files coming in to date partitioned ADLS folders in a scheme of:

root/version/yyyy/mm/dd

each day has from 500K to 750K
each file is 1.5K json 
files flow in over a 6am-12am (18hr) window (roughly 500-600 files/minute)

Databricks can handle this no problem but we are really struggling with how to setup the "drop/landingzone" folder structure.

The reason being is that Autoloader does this periodic backfill.

This folder structure we have, we already have almost a year's worth of data. 185M files altogether. Again, Databricks can handle that no problem as well. But it's when it does this backfill, it starts at the root date and it takes about 2-3min per day-folder to simply do a file-listing, and we don't care about them, **from the real-time aspect.** All that data is historic which we want to load into Delta but we feel like Autoloader is going to go out to lunch for 6-7 hours (and that's just currently, what about when we get 2,3, - 6yrs out)

The use-case is a store manager wants to see "Current Day Sales vs what happend on this day last year".

It feels like the sales data streaming in should be in it's own folder divorced from the "historic" data, but autoloader doesn't work that way.

Should we use the EventGrid notification of Autoloader (is that going to prevent the BackFill process from taking forever)? Or do we need to figure out how to get this into an EventHub/Kafka like scenario so that we can control what we're pulling from the queues?

Feels like we're so close

and lastly, should we be creating "large 1gb json files"? I noticed in many of your blog posts that you seem to be dealing successfully with lots of small json.

Thanks again and we are working with MSFT and Databricks but this particular problem no one seems to have answered for us yet.

**Comment by mdrakiburrahman** [comment]
Gotcha, so basically the problem you're facing is, Autoloader going into traverse each of the folders to enumerate the files is taking time today, and you're worried the pipeline won't be scalable when there's a lot more files in over the years.

So to start, the way I'd approach this problem is going beyond Autoloader. If you haven't looked into doing a POC of this data pipeline using DLT - [Delta Live Tables](https://www.youtube.com/watch?v=zo6K6g2jfqY&ab_channel=Databricks) - I'd highly recommend doing so.

Basically, DLT is a higher-level toolkit abstraction Databricks built on top of Autoloader (though they don't market it that way, that's what they built). In other words, Autoloader is the foundation, DLT is the Data Processing toolset that interfaces Autoloader and offers a bunch of Databricks specific UI/APIs that are delightful to use as a Data Engineer. You can certainly do everything barebones via Autoloader and your own Spark jobs (I'm guessing that's where you saw my blogs), but then you won't get the advantage of some of the luxuries DLT already brings OOTB - such as Pipeline update modes with [**Refresh settings**](https://learn.microsoft.com/en-us/azure/databricks/workflows/delta-live-tables/delta-live-tables-concepts#--pipeline-updates) (it's aligned to the enumeration problem you mentioned above, how do you tell Databricks _"don't refresh the files you've already read, just grab the diff from your last load"_) - e.g. from the docs:


![image](https://user-images.githubusercontent.com/46581776/204140894-702fc363-64b9-46de-afd9-2d6d0326976d.png)

The magic behind DLT is (based on when I played around a few months back and peeked through the DLT ADLS storage structure), DLT keeps a _managed Delta Table_ that holds **metadata** about it's last watermark. In other words, it'll hold your Current Day Sales data in `SalesDataTable` that your end user queries, but then it will also keep a Databricks "managed DLT table" which is literally another Delta table that DLT uses to "know" which is the last set of files it pumped into `SalesDataTable` - [see here](https://www.databricks.com/discover/pages/getting-started-with-delta-live-tables) - so that the next DLT run doesn't go and read everything from `t=0`, and is smart about it's execution:


![image](https://user-images.githubusercontent.com/46581776/204141103-c4ef092c-e226-4784-86e9-edddad2d1e96.png)

> ^With just Autoloader, you'd be reinventing the wheel from scratch here, it's a non-trivial problem to solve at scale - Databricks is in the business of doing this for it's thousands of customers.

This fellow, Simon Whitley has a lot of great starter tutorials on [getting started with it](https://www.youtube.com/watch?v=cjXkhmxi-aY&t=1268s&ab_channel=AdvancingAnalytics).

So in your position, what I'd do is:
* Ramp up on DLT (go through videos, MSFT docs, tutorials etc - get a sense of the tooling available)
* Do a dummy POC of your existing pipeline and ADLS, except with DLT E2E, measure the execution times
* You mentioned you have access to MSFT and Databricks, I'd ask the Solution Architects at Databricks very pointed question about DLT optimization that corresponds to your use case (Databricks is pouring a ton of resources into DLT nowadays, it's their creme de la creme offering that bundles everything about their tech stack into a nice engineering framework that is actually really good)
  * I'd also recommend joining the [Delta Slack](https://delta.io/community/), there's a bunch of folks discussing DLT there and some of the core maintainers

Also:
* **Kafka**: I probably wouldn't introduce Kafka into the architecture here. You've already got your JSON payloads in ADLS partitioned by datetime by Azure Functions, that's literally the same as a Kafka Topic. You'd also have to figure out what Kafka "tech" you'd use - e.g. with Event Hub, you wouldn't get unlimited topic retention (so you'd have to dump data back into ADLS anyway). You could consider Confluent - it's great and premium, but it's expensive and overkill because it doesn't sound like your Store Manger needs _real time_ (as far as latency go, your Point-of-sale system probably isn't realtime in sending updates, so having real-time analytics is meaningless for a handful of people running random queries throughout the day). You'd also have to figure out a new Partitioning strategy for your Topics.

* **Small vs big JSON**: I'd pick small JSON every time. When you run into a problem deserializing a massive JSON file in a Spark Executor, there's not much more you can do besides throwing larger Hardware. There's limited "Spark coding tricks" you'll find on the internet about deserializing a massive JSON payload `<--- This is not a problem Databricks or any other company in the world is spending money to build tech to solve, you will be in a unique situation where the answer is larger VMs with more RAM`
 
  On the other hand, with Small JSON, the problem you need to solve is the watermark problem - _how do I get DLT to skip over millions of small files it's already read_ `<--- This is the same problem every Databricks customer is/will face, there must/will be a canonical pattern to solve this in DLT, otherwise Databricks as an analytics platform running on ADLS is useless`.

By the way, I'm not actually hands on in Databricks anymore as I've switched roles, working on a different tech stack (so if you have any specific Databricks implementation questions, unfortunately I won't be of much help as I haven't been keeping up with the latest and greatest.)

Hope that helps and best of luck!

**Comment by jonathandbyrd** [comment]
oh man, i could have saved you so much time. We're using Delta Live Tables, and yes, they work great. The issue though, as i pointed out is still with Autoloader which is why i focused on it. DLT is just a wrapper/pipeline as you said and bakes in all kinds of cool things like your checkpoint locations, schema drift handling and the scheduling etc.

i wrote this up in the Delta Lake slack channel, may help you even more understand what i did, its clearer i think.
https://delta-users.slack.com/archives/CJ70UCSHM/p1669692319898829

btw, thanks so much for all your help and suggestions

**Comment by mdrakiburrahman** [comment]
Hey @jonathandbyrd - sorry I haven't been keeping a close eye on the repo, hopefully you've been able to figure out the solution!

If you wanted to share how you approached it, I'd love to learn - thanks for reaching out!
