### ISSUE TITLE
SQL Replication follow up question

### ISSUE THREAD

**Issue by iamhasib** [mdrakiburrahman/rakirahman.me#7]
Salaam Raki. 

Firstly, a quick question about something different. I checked some other post on your blog site. Did you draw your diagram and artwork that you published on your page? Which tool you used to draw those diagrams, specially those with code snippet.

Now about your solution. I comment on the last one first. Event driven one. I would love to do that but wouldn't you agree that would be a massive project. I ran CDC project and they are complex. However you simplify it, CDC is always complicated.

As of Replication based, even cost wise, it's cheaper (than ADF). I saw a video about ADF pricing, man...this is major ....Back to replication, I am not sure if I fully understood as to what you were saying on Preview. Does feature in preview means it's not available in AU region?

I look forward to hearing from you soon.

**Comment by iamhasib** [comment]
About having watermark column, it always makes me uncomfortable. But the below tells me it's possible to have CDC without the need of watermark column - 

https://docs.microsoft.com/en-us/azure/data-factory/tutorial-incremental-copy-change-data-capture-feature-portal

**Comment by mdrakiburrahman** [comment]
Walaikum Salam - My apologies for the extremely late reply, I had missed this.

I use PowerPoint for the blog. "Preview" in Microsoft terms refers to guaranteed SLAs and not regional availability. In the link you posted, Data Factory is actually made to read from the CDC tables in Azure SQL MI. Reading these same tables using a CDC tool like Debezium achieves exactly the same thing, except the latency for Data Factory is higher because it's batch processing (5 minutes for ADF vs 5 seconds for Debezium).
